# Generated by Django 4.1.7 on 2023-03-15 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vk_bot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название товара"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Товар доступен?"),
                ),
                (
                    "description",
                    models.CharField(
                        default=None,
                        max_length=255,
                        null=True,
                        verbose_name="Описание товара",
                    ),
                ),
                (
                    "vk_photo_id",
                    models.CharField(
                        default=None,
                        help_text="Например: photo-123456_654231",
                        max_length=50,
                        null=True,
                        verbose_name="Ссылка на фото товара в вк группе",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="vk_bot.productscategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "db_table": "product",
                "unique_together": {("category", "name")},
            },
        ),
    ]
